/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PatelDev (https://sketchfab.com/PatelDev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import AirplaneModel from "./AirplaneModel";

function EarthComponent(props) {
  const { nodes, materials } = useGLTF("/earth/earth.gltf");
  return (
    <React.Fragment>
      <group {...props} dispose={null} scale={1.1}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group scale={1.13}>
              <mesh
                geometry={nodes.Object_4.geometry}
                material={materials["Scene_-_Root"]}
              />
            </group>
          </group>
        </group>
      </group>
      {/* <AirplaneModel /> */}
    </React.Fragment>
  );
}

useGLTF.preload("/earth/earth.gltf");

export default EarthComponent;
